### ISSUE TITLE
No analytics code is added to html pages

### ISSUE THREAD

**Issue by Roald87** [hendrikschneider/jekyll-analytics#53]
I'm trying to add Plausible analytics to my GitHub pages site. I assume that when everything works, the following snippet should be added somewhere between the `<head>` tags: 

```
<script async defer data-domain="roald87.github.io" src="https://plausible.io/js/plausible.js"></script>
```

I did the following:
1. Added `gem 'jekyll-analytics'` to my `Gemfile` 
2. Did `bundle install`, where I see the following line in the output: `Using jekyll-analytics 0.1.14` 
3. Added the following to my `_config.yml` file:
    ```
    plugins:
      - jekyll-analytics
    whitelist: [jekyll-analytics]

    Plausible:
      domain: 'roald87.github.io'   # The domain configured in plausible
      source: 'https://plausible.io/js/plausible.js' # The source of the javascript
    ```
4. Did `bundle exec jekyll serve JEKYLL_ENV=production`

When I inspect the index.html no analytics tag is added in the head. I also tested it with the GoogleAnalytics one, by replacing the `Plausible: ...` with:

```
GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-123-456          # Required - replace with your tracking id
    anonymizeIp: true      # Optional - Default: false - set to true for anonymized tracking
```

But again with the same result.

When I check the verbose output of `jekyll serve` I do no see the jekyll-analytics module being used anywhere:

```
$ bundle exec jekyll serve --verbose JEKYLL_ENV=production | grep "Requiring"
         Requiring: jekyll-github-metadata
         Requiring: jekyll-seo-tag
         Requiring: jekyll-feed
         Requiring: jemoji
         Requiring: jekyll-coffeescript
         Requiring: jekyll-commonmark-ghpages
         Requiring: jekyll-gist
         Requiring: jekyll-github-metadata
         Requiring: jekyll-paginate
         Requiring: jekyll-relative-links
         Requiring: jekyll-optional-front-matter
         Requiring: jekyll-readme-index
         Requiring: jekyll-default-layout
         Requiring: jekyll-titles-from-headings
         Requiring: jekyll-remote-theme
         Requiring: jekyll-seo-tag
         Requiring: kramdown-parser-gfm
/home/roald/gems/gems/pathutil-0.16.2/lib/pathutil.rb:502: warning: Using the last argument as keyword parameters is deprecated
         Requiring: jekyll-watch
```

Or doesn't it show up in here?

Am I doing something wrong here?
