### ISSUE TITLE
Using the plugin for plausible

### ISSUE THREAD

**Issue by erin-bristow** [hendrikschneider/jekyll-analytics#72]
Used [this issue]( https://github.com/hendrikschneider/jekyll-analytics/issues/47) to attempt to make it work, because it didn't work when I followed the main README.md guide

I can see Plausible present in the Console developer view for my site ([ebristow.com](https://ebristow.com)), but when I reload the page it doesn't show up under Network so it doesn't look like it's reaching out to Plausible. Any help is appreciated - thank you!

In _config.yml:
```
plugins:
  - jekyll-feed
  - jekyll-target-blank
  - jekyll-analytics

jekyll_analytics:
  Plausible:
    domain: 'ebristow.com'   # The domain configured in plausible
    source: 'https://plausible.io/js/plausible.js' # The source of the javascript
```

In Gemfile:
`group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-analytics", "~> 0.1", git: 'https://github.com/hendrikschneider/jekyll-analytics', ref: '40e09570dea80e3a9ecb0ad796aad1c434ff067c' # https://github.com/hendrikschneider/jekyll-analytics
end`
